"""empty message

Revision ID: 3a9821f6541d
Revises: None
Create Date: 2014-10-23 12:50:58.341679

"""

# revision identifiers, used by Alembic.
revision = '3a9821f6541d'
down_revision = None

from alembic import op
from sqlalchemy_utils.types.password import PasswordType
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', PasswordType(schemes=['pbkdf2_sha512']), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
